title: <p align="center"> Sandeep Kumar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sandeep-kumar-lavish/">LinkedIn</a> |
  <a href="https://github.com/sandeepkumar15140">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  I am a Senior Software Engineer.
  Learning ML and  AI.
  <br>
  </p>



theme: jekyll-theme-minimal
